AZURE_OPENAI_API_KEY = "7MoKzuuPAla0Cl3RYSM2aHjTAmkVopeVC4VhHCCdLPGDbAg0Vk4OJQQJ99AKACYeBjFXJ3w3AAABACOGrjrr"
API_VERSION = "2024-10-01-preview"
API_ENDPOINT = "https://practicas-2024.openai.azure.com/"
API_LOCATION = "eastus"

API_MODEL_MINI = "gpt-4o-mini"
API_MODEL = "gpt-4o"

